Repository ichiro-its/keisan, pull requests merged in 2021-04, with the labels that each got.

#4 Add build and test workflow
  .github/workflows/build-and-test.yml
  README.md
Labels: enhancement, good first issue

#5 Add Point Struct
  CMakeLists.txt
  include/keisan/keisan.hpp
  include/keisan/point_2.hpp
  include/keisan/point_3.hpp
  src/point_2.cpp
  src/point_3.cpp
Labels: enhancement, good first issue

#10 Add Test for Points
  CMakeLists.txt
  src/point_2.cpp
  src/point_3.cpp
  test/point_2_test.cpp
  test/point_3_test.cpp
Labels: enhancement, good first issue

#9 Add a Scale Number function
  include/keisan/number.hpp
  src/angle.cpp
  src/number.cpp
  test/number_test.cpp
Labels: enhancement, good first issue

#13 Add Distance Equation in Point Structs
  README.md
  include/keisan/point_2.hpp
  include/keisan/point_3.hpp
  src/point_2.cpp
  src/point_3.cpp
  test/point_2_test.cpp
  test/point_3_test.cpp
Labels: enhancement

#14 Add Delta Angle Equation
  include/keisan/angle.hpp
  src/angle.cpp
  test/angle_test.cpp
Labels: enhancement

#18 Add support to clamp number
  include/keisan/number.hpp
  src/number.cpp
  test/number_test.cpp
Labels: enhancement, good first issue

#17 Add Direction Equation
  README.md
  include/keisan/point_2.hpp
  include/keisan/point_3.hpp
  src/angle.cpp
  src/point_2.cpp
  src/point_3.cpp
  test/point_2_test.cpp
  test/point_3_test.cpp
Labels: enhancement

#20 Add Supoort for Dot Product and Cross Product
  include/keisan/point_2.hpp
  include/keisan/point_3.hpp
  src/point_2.cpp
  src/point_3.cpp
  test/point_2_test.cpp
  test/point_3_test.cpp
Labels: enhancement

#22 21 wrong result in point2 direction
  CMakeLists.txt
  LICENSE
  README.md
  include/keisan/angle.hpp
  include/keisan/keisan.hpp
  include/keisan/number.hpp
  include/keisan/point_2.hpp
  include/keisan/point_3.hpp
  package.xml
  src/angle.cpp
  src/number.cpp
  src/point_2.cpp
  src/point_3.cpp
  test/angle_test.cpp
  test/number_test.cpp
  test/point_2_test.cpp
  test/point_3_test.cpp
Labels: bug
